# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2016/11/30/setting-up-gitlab-ci-for-android-projects/, by Greyson Parrelli
image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.1"
  ANDROID_SDK_TOOLS_REV: "4333796"


before_script:
  - mkdir $HOME/.android # For sdkmanager configs
  - echo 'count=0' > $HOME/.android/repositories.cfg # Avoid warning
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS_REV}.zip
  - mkdir $PWD/android-sdk-linux
  - unzip -qq android-sdk.zip -d $PWD/android-sdk-linux
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/platform-tools/:$ANDROID_NDK_HOME
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager --update
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'tools'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platform-tools'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'build-tools;'$ANDROID_BUILD_TOOLS
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-'$ANDROID_COMPILE_SDK
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;android;m2repository'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;google_play_services'
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;m2repository'
  - chmod +x ./gradlew


stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace
  artifacts:
    paths:
    - app/build/outputs/